### ISSUE TITLE
Cant install on Windows 11

### ISSUE THREAD

**Issue by dinocaminos44** [Juceten/Accepter2#1]
![image](https://user-images.githubusercontent.com/91952878/155397903-c02364c3-0ad5-4e0e-82f0-c3f94a77d7b5.png)
I keep getting this error, please if this is still alive, answer me

**Comment by dinocaminos44** [comment]
> 

"python" is not recognized as an internal or external command,
program or executable batch file.
The system cannot find the specified path.
"pip" is not recognized as an internal or external command,
program or executable batch file.
"deactivate" is not recognized as an internal or external command, program or executable batch file,
program or executable batch file.
Press a key to continue . . .
its says this in spanish

**Comment by Juceten** [comment]
> > 
> 
> "python" is not recognized as an internal or external command, program or executable batch file. The system cannot find the specified path. "pip" is not recognized as an internal or external command, program or executable batch file. "deactivate" is not recognized as an internal or external command, program or executable batch file, program or executable batch file. Press a key to continue . . . its says this in spanish

The issue is stated in the error messages. You need to ensure python is installed and that it is added to your system's PATH. You can verify this by opening a command prompt and typing " python -V " (without the quotes and make sure to caps the V). If it gives you a version of python you are good to go if you get an error, you need to add python to your systems PATH or install python. You can simply google how to perform this action.
